providers:
  - airtap-sauce
sauce_connect: true
browsers:
  - name: chrome
  - name: firefox
  - name: safari
  - name: edge

presets:
  local:
    providers:
      - airtap-playwright
    browsers:
      - name: chromium
      - name: firefox
      - name: webkit
      - name: chromium
        options:
          launch:
            channel: msedge
