browsers:
  - name: ie
    version: 11..latest
  - name: opera
    version: -3..latest
  - name: chrome
    version: -3..latest
  - name: firefox
    version: -3..latest
  - name: safari
    version: 5..latest
  - name: microsoftedge
    version: -3..latest
