presets:
  all:
    providers:
      - airtap-playwright
    browsers:
      - name: chromium
      - name: firefox
      - name: webkit
      - name: chromium
        options:
          launch:
            channel: msedge

  chrome:
    providers:
      - airtap-playwright
    browsers:
      - name: chromium

  firefox:
    providers:
      - airtap-playwright
    browsers:
      - name: firefox

  safari:
    providers:
      - airtap-playwright
    browsers:
      - name: webkit

  edge:
    providers:
      - airtap-playwright
    browsers:
      - name: chromium
        options:
          launch:
            channel: msedge
