sudo: false
language: node_js
notifications:
  email: false
matrix:
  fast_finish: true
  include:
  - node_js: 6
    env: CMD=test
  - node_js: 8
    env: CMD=test
  - node_js: 9
    env: CMD=test
  - node_js: 10
    env: CMD=test
  - node_js: stable
    env: CMD=test-browsers
    addons:
      sauce_connect: true
      hosts:
        - airtap.local
script: npm run $CMD
env:
  global:
  - secure: rE2Vvo7vnjabYNULNyLFxOyt98BoJexDqsiOnfiD6kLYYsiQGfr/sbZkPMOFm9qfQG7pjqx+zZWZjGSswhTt+626C0t/njXqug7Yps4c3dFblzGfreQHp7wNX5TFsvrxd6dAowVasMp61sJcRnB2w8cUzoe3RAYUDHyiHktwqMc=
  - secure: g9YINaKAdMatsJ28G9jCGbSaguXCyxSTy+pBO6Ch0Cf57ZLOTka3HqDj8p3nV28LUIHZ3ut5WO43CeYKwt4AUtLpBS3a0dndHdY6D83uY6b2qh5hXlrcbeQTq2cvw2y95F7hm4D1kwrgZ7ViqaKggRcEupAL69YbJnxeUDKWEdI=
