sudo: false
language: node_js
notifications:
  email: false
matrix:
  fast_finish: true
  include:
  - node_js: 6
    env: CMD=test
  - node_js: 8
    env: CMD=test
  - node_js: 9
    env: CMD=test
  - node_js: 10
    env: CMD=test
  - node_js: stable
    env: CMD=test-browsers
    addons:
      sauce_connect: true
      hosts:
      - airtap.local
script: npm run $CMD
env:
  global:
  - secure: nk/kDUZV385ey9kkrGi6EHvnslTAW+GEHGrjbFIsb8Foq01bL9oj0uPaVc5kaVWCHst3WsIdVMA1Hos/lN/WMHRyfOiSrVVWv0sVnzg0YaM9cBbn5jwXn30Z645REgQcoEDKrYFp8rE3RpPFgYDFWNh948qwPtwtnwNhoq/Gd9A=
  - secure: faODkEUSlbH4fLBll4UkHeSEsCZdW+Hw+Sb6yDX5PXkIgq5wvqALIUgDIEBz2F8gciLlPlIssR2csKPqYIK5uwUq7uPBJVmwcf6i0K9NZaU/WaGaUVCzs2oMAoN007pTU30USEiWzfEGR+0d5hRKoeJdZIU0nBxkpLY4ZWM0SGU=
