name: Bundlers

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: Bundlers
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12.x, 14.x, 16.x, 18.x, 20.x]
        bundler: ['browserify', 'esbuild', 'rollup', 'webpack']
        exclude:
          - os: windows-latest
            node-version: 12.x
          - os: windows-latest
            node-version: 14.x
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ matrix.os }}-${{ hashFiles('package.json') }}
      - name: Install dependencies
        run: npm install
      - name: Bundle code
        run: npm run test:prepare ${{ matrix.bundler }}
      - name: Run Tests on Browsers
        run: npm run test:bundlers ${{ matrix.bundler }}
