name: Lint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    name: Node.js
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package.json') }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Check generated files
        run: |
          # Check if diff is empty
          git diff --exit-code --stat ${{ github.sha }} -- lib/
      - name: Check for lint issues
        run: npm run lint
