name: Node.js

on: [push, pull_request]

jobs:
  build:
    name: Node.js
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [12.x, 14.x, 16.x, 18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node: ${{ matrix.node }}
      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ matrix.os }}-node${{ matrix.node }}-${{ hashFiles('package.json') }}
      - name: Install dependencies
        run: npm install --omit=optional
      - name: Run Tests
        run: npm run coverage
