name: Sauce Labs Build
on: push
jobs:
  test:
    name: Sauce Labs Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: ['chrome', 'firefox', 'edge']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package.json') }}
      - name: Install dependencies
        run: npm install
        env:
          # Download Sauce Connect binary now instead of on first run
          SAUCE_CONNECT_DOWNLOAD_ON_INSTALL: true
      - name: Add airtap.local to /etc/hosts
        run: echo "127.0.0.1 airtap.local" | sudo tee -a /etc/hosts
      - name: Pause to avoid Sauce Labs timeouts
        run: sleep 30s
        shell: bash
      - name: Run Test
        run: ./node_modules/.bin/airtap -p sauce-${{ matrix.browser }} test/browser/test-*.js
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
